CXXFLAGS = -O2 -Wall -std=c++11

HEADERS = graph.h disjointset.h countingsort.h
SOURCES = kruskal.cpp graph.cpp disjointset.cpp countingsort.cpp

kruskal: $(SOURCES) $(HEADERS)

clean:
	$(RM) kruskal *.o
