CXXFLAGS = -O2 -Wall -std=c++11
PQSORT = pqsort.cpp
SORTSORT = sortsort.cpp
KEYVALGEN = keyvalgen.cpp

default: pqsort 

pqsort: $(PQSORT) 

sortsort: $(SORTSORT) 

keyvalgen: $(KEYVALGEN)

clean:
	$(RM) pqsort sortsort keyvalgen

